# Write your MySQL query statement below
WITH CTE AS 
(
        SELECT
        C.CUSTOMER_ID, 
        C.NAME, 
        SUM(O.QUANTITY * P.PRICE) AS AMT,
        MONTH(O.ORDER_DATE) AS MONTH
        FROM CUSTOMERS AS C  LEFT JOIN ORDERS AS O
        ON C.CUSTOMER_ID = O.CUSTOMER_ID LEFT JOIN PRODUCT AS P
        ON O.PRODUCT_ID = P.PRODUCT_ID
        WHERE YEAR(O.ORDER_DATE) = 2020
        GROUP BY C.CUSTOMER_ID, C.NAME , MONTH(O.ORDER_DATE)
)

SELECT CUSTOMER_ID, NAME
FROM CTE
WHERE AMT >= 100 AND MONTH IN (06,07)
GROUP BY CUSTOMER_ID, NAME
HAVING COUNT(*) = 2